# Generated by Django 5.2.7 on 2025-10-27 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca_app", "0002_libro_disponible_libro_fecha_creacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario_nombre", models.CharField(max_length=100)),
                ("usuario_email", models.EmailField(max_length=254)),
                ("fecha_reserva", models.DateTimeField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateTimeField()),
                ("fecha_devolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                            ("vencida", "Vencida"),
                        ],
                        default="activa",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="biblioteca_app.libro",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_reserva"],
            },
        ),
    ]
